CC=gcc
LEX=flex
YACC=bison -y
YFLAGS=-d
CC_LEX_FLAGS=fl
CC_FLAGS=-g
MKDIR=mkdir -p

ROOT_DIR=.
SOURCE_DIR=${ROOT_DIR}/src
TEST_DIR=${ROOT_DIR}/test
BUILD_DIR=${ROOT_DIR}/build
BUILD_OBJ_DIR=${BUILD_DIR}/obj
BUILD_GEN_DIR=${BUILD_DIR}/src
BUILD_EXE_DIR=${BUILD_DIR}/exec
BUILD_TEST_DIR=${BUILD_DIR}/test

BIN2HEX_EXE=${BUILD_EXE_DIR}/bin2hex
HEX2BIN_EXE=${BUILD_EXE_DIR}/hex2bin
SEXTIUM_EXE=${BUILD_EXE_DIR}/sextium
DEASM_EXE=${BUILD_EXE_DIR}/deasm
ASM_EXE=${BUILD_EXE_DIR}/asm
DCOMP_EXE=${BUILD_EXE_DIR}/dcomp

TRACE_OBJECTS = ${BUILD_OBJ_DIR}/trace.o
TRACE_SOURCES = ${TRACE_OBJECTS:${BUILD_OBJ_DIR}/%.o=${SOURCE_DIR}/%.c}
TRACE_HEADERS = ${SOURCE_DIR}/trace.h

BIN2HEX_OBJECTS = ${BUILD_OBJ_DIR}/bin2hex.o
HEX2BIN_OBJECTS = ${BUILD_OBJ_DIR}/hex2bin.o
SEXTIUM_OBJECTS = ${BUILD_OBJ_DIR}/sextium.o
DEASM_OBJECTS = ${BUILD_OBJ_DIR}/deasm.o
ASM_OBJECTS = ${BUILD_OBJ_DIR}/sextium_asm.tab.o ${BUILD_OBJ_DIR}/sextium_asm.yy.o ${BUILD_OBJ_DIR}/asm_types.o
DCOMP_OBJECTS = ${BUILD_OBJ_DIR}/dcomp.tab.o ${BUILD_OBJ_DIR}/dcomp.yy.o ${BUILD_OBJ_DIR}/dcomp_types.o ${BUILD_OBJ_DIR}/asm_types.o

.SECONDARY:

TESTS = gcd sum
TEST_BINS = ${TESTS:%=${BUILD_TEST_DIR}/%.bin}

all: ${BIN2HEX_EXE} ${HEX2BIN_EXE} ${SEXTIUM_EXE} ${DEASM_EXE} ${ASM_EXE} ${DCOMP_EXE}

${TRACE_OBJECTS}:${TRACE_HEADERS}

${BIN2HEX_OBJECTS}:${TRACE_HEADERS}

${HEX2BIN_OBJECTS}:${TRACE_HEADERS}

${SEXTIUM_OBJECTS}:${TRACE_HEADERS}

${DEASM_OBJECTS}:${TRACE_HEADERS}

${ASM_OBJECTS}:${TRACE_HEADERS}

${DCOMP_OBJECTS}:${TRACE_HEADERS}

${BUILD_OBJ_DIR}/%.tab.o:${BUILD_GEN_DIR}/%.tab.c ${BUILD_OBJ_DIR}
	${CC} ${CC_FLAGS} -I${SOURCE_DIR} -c ${BUILD_GEN_DIR}/$*.tab.c -o ${BUILD_OBJ_DIR}/$*.tab.o

${BUILD_OBJ_DIR}/%.yy.o:${BUILD_GEN_DIR}/%.yy.c ${BUILD_GEN_DIR}/%.tab.c ${BUILD_OBJ_DIR}
	${CC} ${CC_FLAGS} -I${SOURCE_DIR} -c ${BUILD_GEN_DIR}/$*.yy.c -o ${BUILD_OBJ_DIR}/$*.yy.o

${BUILD_OBJ_DIR}/%.o:${SOURCE_DIR}/%.c ${BUILD_OBJ_DIR}
	${CC} ${CC_FLAGS} -c ${SOURCE_DIR}/$*.c -o ${BUILD_OBJ_DIR}/$*.o

${BUILD_GEN_DIR}/%.tab.c:${SOURCE_DIR}/%.y ${BUILD_GEN_DIR}
	${YACC} ${YFLAGS} ${SOURCE_DIR}/$*.y -o ${BUILD_GEN_DIR}/$*.tab.c

${BUILD_GEN_DIR}/%.yy.c:${SOURCE_DIR}/%.l ${BUILD_GEN_DIR}
	${LEX} -o ${BUILD_GEN_DIR}/$*.yy.c ${SOURCE_DIR}/$*.l

${BIN2HEX_EXE}:${TRACE_OBJECTS} ${BIN2HEX_OBJECTS} ${BUILD_EXE_DIR}
	${CC} ${CC_FLAGS} ${TRACE_OBJECTS} ${BIN2HEX_OBJECTS} -o ${BIN2HEX_EXE}

${HEX2BIN_EXE}:${TRACE_OBJECTS} ${HEX2BIN_OBJECTS} ${BUILD_EXE_DIR}
	${CC} ${CC_FLAGS} ${TRACE_OBJECTS} ${HEX2BIN_OBJECTS} -o ${HEX2BIN_EXE}

${SEXTIUM_EXE}:${TRACE_OBJECTS} ${SEXTIUM_OBJECTS} ${BUILD_EXE_DIR}
	${CC} ${CC_FLAGS} ${TRACE_OBJECTS} ${SEXTIUM_OBJECTS} -o ${SEXTIUM_EXE}

${DEASM_EXE}:${TRACE_OBJECTS} ${DEASM_OBJECTS} ${BUILD_EXE_DIR}
	${CC} ${CC_FLAGS} ${TRACE_OBJECTS} ${DEASM_OBJECTS} -o ${DEASM_EXE}

${ASM_EXE}:${TRACE_OBJECTS} ${ASM_OBJECTS} ${BUILD_EXE_DIR}
	${CC} ${CC_FLAGS} ${ASM_OBJECTS} ${TRACE_OBJECTS} -l${CC_LEX_FLAGS} -o ${ASM_EXE}

${DCOMP_EXE}:${TRACE_OBJECTS} ${DCOMP_OBJECTS} ${BUILD_EXE_DIR}
	${CC} ${CC_FLAGS} ${DCOMP_OBJECTS} ${TRACE_OBJECTS} -l${CC_LEX_FLAGS} -o ${DCOMP_EXE}

${BUILD_TEST_DIR}/%.bin:${TEST_DIR}/%.hex ${HEX2BIN_EXE} ${BUILD_TEST_DIR}
	${HEX2BIN_EXE} ${TEST_DIR}/$*.hex ${BUILD_TEST_DIR}/$*.bin	

test:${BIN2HEX_EXE} ${HEX2BIN_EXE} ${SEXTIUM_EXE} ${TEST_BINS}

${BUILD_OBJ_DIR}:${BUILD_DIR}
	${MKDIR} ${BUILD_OBJ_DIR}

${BUILD_GEN_DIR}:${BUILD_DIR}
	${MKDIR} ${BUILD_GEN_DIR}

${BUILD_EXE_DIR}:${BUILD_DIR}
	${MKDIR} ${BUILD_EXE_DIR}

${BUILD_TEST_DIR}:${BUILD_DIR}
	${MKDIR} ${BUILD_TEST_DIR}

${BUILD_DIR}:
	${MKDIR} ${BUILD_DIR}

clean:
	rm -f ${BIN2HEX_EXE}
	rm -f ${HEX2BIN_EXE}
	rm -f ${SEXTIUM_EXE}
	rm -f ${DEASM_EXE}
	rm -f ${ASM_EXE}
	rm -f ${TRACE_OBJECTS}
	rm -f ${BIN2HEX_OBJECTS}
	rm -f ${HEX2BIN_OBJECTS}
	rm -f ${SEXTIUM_OBJECTS}
	rm -f ${DEASM_OBJECTS}
	rm -f ${ASM_OBJECTS}
	rm -f ${TEST_BINS}
